### ISSUE TITLE
Implementación de Agregadores

### ISSUE THREAD

**Issue by hector23rp** [hector23rp/ACME-Explorer-CodeJOH#30]

**Comment by hector23rp** [comment]
Puntos en los requisitos del proyecto donde podemos poner Agregaciones:
- 8.1.
- 8.2.
- 9.2.
- 15.3. 
- 21.2

**Comment by hector23rp** [comment]
- TopCancellers
- TopConsumers/TopNotCancellers
- BottomNotCancellers
- TopClerks
- BotomClerks
- Ratio of orders cancelled during current month

**Comment by omigongar** [comment]
Hechas 9.2.1, 9.2.3

**Comment by joseanteugfer** [comment]
Hecha la 15.3

**Comment by omigongar** [comment]
Falta punto 21
