### ISSUE TITLE
Creación de los controladores del DataWareHouse

### ISSUE THREAD

**Issue by hector23rp** [hector23rp/ACME-Explorer-CodeJOH#33]
Se deben crear los siguientes controladores:
- 	Controlador para crear el cron Job y definir el trabajo que se ejecuta. Este trabajo es realizar de forma paralela todas funciones (cada función ejecuta una agregación)
- 	Un método para devolver todos los valores. Utilizar find sobre el DataWareHouse (caché de mongo)
- 	Un método para devolver el último
- 	Un método para cambiar la periodicidad. Utilizar reconfigure de Cron.
-      Un método por cada operación de agregación

**Comment by omigongar** [comment]
Punto 1 - Complete
Punto 2 - Complete
Punto 3 - Complete
Punto 4 - Test
Queda implementar las agregaciones

**Comment by omigongar** [comment]
Punto 4 - Complete
Implementadas las agregaciones
