### ISSUE TITLE
Guardar imagen en Trip

### ISSUE THREAD

**Issue by hector23rp** [hector23rp/ACME-Explorer-CodeJOH#41]
Crear una ruta PUT que se encargue de agregar una imagen a un Trip existente.

Librerías para subir ficheros a la API:
https://stackoverflow.com/questions/53416456/reading-png-image-from-request-using-body-parser-and-express

**Comment by omigongar** [comment]
Modificar el modelo para considerar las imágenes como url.
Chequear que los request se hagan bien, usar swagger
