### ISSUE TITLE
Generar un JSON de actores con un gran cantidad

### ISSUE THREAD

**Issue by hector23rp** [hector23rp/ACME-Explorer-CodeJOH#54]
next.json-generator.com

**Comment by joseanteugfer** [comment]
El programa sólo te deja crear de 100 en 100 y si replicas, te permite hacer un JSON con 2000. He creado uno con 2000 y pesa apenas 1 MB. Para hacer un más grande habría que copiar y pegar y quitar la restricción del unique del email

**Comment by hector23rp** [comment]
Ook perfecto. Pues dejamos este JSON y luego crearemos otro quitando la restricción para hacer la prueba
