### ISSUE TITLE
Crear nuevo atributo para guardar resultado de finder

### ISSUE THREAD

**Issue by joseanteugfer** [hector23rp/ACME-Explorer-CodeJOH#58]
- Añadir el campo al modelo de actor
- Al realizar la búsqueda de viajes, cachear resultado en el nuevo campo del modelo
- Checkear tiempo de cacheo para ver si hacemos la llamada al finder o devolvemos los datos de la caché.

**Comment by omigongar** [comment]
Debe tener un campo para indicar el momento en que se efectuó la consulta ya que hay que usarlo junto al modelo de config para chequear si se debe o no volver a realizar la consulta
