### ISSUE TITLE
Issue Dashboard

### ISSUE THREAD

**Issue by hector23rp** [hector23rp/ACME-Explorer-CodeJOH#65]
- Función computeTopKeywordsFinders: en el campo keywords devuelve null
- Función computeavgPriceRangeFinders: en el campo avgPriceRangeFinders devuelve null
- En la llamada rebuildPeriod, cuando actualiza el período se debe poner en el formato adecuado (Ejemplo, si se envía 100 debe poner */100 *****)

**Comment by joseanteugfer** [comment]
el segundo punto está resuelto en lo último subido en la rama actor (26/03/19)
